import { Expert } from './types';

export const expertDummy: Expert[] = [
  {
    id: '1',
    user: {
      id: '101',
      name: '김철수',
      gender: 'male',
    },
    available_location: ['서울특별시', '경기도 성남시'],
    appeal: '100명 이상의 결혼식을 성공적으로 진행했습니다.',
    service: '결혼식 사회자',
    careers: [
      {
        title: '결혼식 사회자',
        description: '중소규모 결혼식 전문 사회 진행',
        start_date: '2020-05-10',
        end_date: '2023-09-20',
      },
    ],
    expert_image: 'https://example.com/images/chulsoo.jpg',
  },
  {
    id: '2',
    user: {
      id: '102',
      name: '이영희',
      gender: 'female',
    },
    available_location: ['부산광역시', '경상남도 창원시'],
    appeal: '300명 이상의 대형 세미나를 전문적으로 진행한 경력이 있습니다.',
    service: '세미나 사회자',
    careers: [
      {
        title: '세미나 사회자',
        description: '대형 세미나 및 컨퍼런스 전문 진행',
        start_date: '2018-03-15',
        end_date: '2023-08-30',
      },
    ],
    expert_image: 'https://example.com/images/younghee.jpg',
  },
  {
    id: '3',
    user: {
      id: '103',
      name: '박민수',
      gender: 'male',
    },
    available_location: ['대전광역시', '충청북도 청주시'],
    appeal: '이벤트 행사 사회자로 5년 이상 활동한 경험이 있습니다.',
    service: '이벤트 사회자',
    careers: [
      {
        title: '이벤트 사회자',
        description: '지역 축제 및 기업 이벤트 진행',
        start_date: '2015-06-01',
        end_date: '2022-12-15',
      },
    ],
    expert_image: 'https://example.com/images/minsoo.jpg',
  },
  {
    id: '4',
    user: {
      id: '104',
      name: '최은지',
      gender: 'female',
    },
    available_location: ['광주광역시', '전라남도 목포시'],
    appeal: '각종 스포츠 경기 개막식 사회를 전문으로 합니다.',
    service: '스포츠 경기 사회자',
    careers: [
      {
        title: '스포츠 경기 사회자',
        description: '지역 및 전국 단위 경기 진행',
        start_date: '2017-04-20',
        end_date: '2023-05-15',
      },
    ],
    expert_image: 'https://example.com/images/eunji.jpg',
  },
  {
    id: '5',
    user: {
      id: '105',
      name: '정현우',
      gender: 'male',
    },
    available_location: ['제주특별자치도'],
    appeal: '제주 지역의 소규모 결혼식에 최적화된 사회 서비스를 제공합니다.',
    service: '소규모 결혼식 사회자',
    careers: [
      {
        title: '소규모 결혼식 사회자',
        description: '제주 지역 결혼식 전문',
        start_date: '2019-01-01',
        end_date: null,
      },
    ],
    expert_image: 'https://example.com/images/hyunwoo.jpg',
  },
];

export const reservationsDummy = [
  {
    id: 1,
    status: '예약 확정',
    estimation: {
      id: 1,
      request_id: 3,
      expert_id: 4,
      location: '경기도 광주',
      due_date: '2024-12-24 12:20:00',
      service: '결혼식 사회자',
      charge: 270000,
      created_at: '2024-11-23 12:02:30',
      request_user: {
        id: 3,
        name: '권순율',
        phone: '010-1234-1234',
      },
      expert: {
        user_id: 4,
        email: 'example@example.com',
        phone: '010-5678-5678',
        name: '홍길동',
        profile_image: 'ImageFile1',
      },
    },
  },
  {
    id: 2,
    status: '서비스 완료',
    estimation: {
      id: 2,
      request_id: 6,
      expert_id: 7,
      location: '서울 강남구',
      due_date: '2025-01-05 15:00:00',
      service: '스냅 촬영',
      charge: 1500000,
      created_at: '2024-11-22 10:45:00',
      request_user: {
        id: 6,
        name: '김민수',
        phone: '010-3456-3456',
      },
      expert: {
        user_id: 7,
        email: 'photographer@example.com',
        phone: '010-9876-5432',
        name: '이영호',
        profile_image: 'ImageFile2',
      },
    },
  },
  {
    id: 3,
    status: '예약 취소',
    estimation: {
      id: 3,
      request_id: 9,
      expert_id: 11,
      location: '부산 해운대구',
      due_date: '2024-12-30 14:00:00',
      service: '결혼식 사회자',
      charge: 500000,
      created_at: '2024-11-20 09:30:00',
      request_user: {
        id: 9,
        name: '최지혜',
        phone: '010-8765-8765',
      },
      expert: {
        user_id: 11,
        email: 'planner@example.com',
        phone: '010-6543-2109',
        name: '박지훈',
        profile_image: 'ImageFile3',
      },
    },
  },
  {
    id: 4,
    status: '채팅 중',
    estimation: {
      id: 4,
      request_id: 12,
      expert_id: 15,
      location: '인천 남동구',
      due_date: '2024-12-15 11:00:00',
      service: '영상 촬영',
      charge: 800000,
      created_at: '2024-11-15 13:00:00',
      request_user: {
        id: 12,
        name: '윤아름',
        phone: '010-3456-2345',
      },
      expert: {
        user_id: 15,
        email: 'makeupartist@example.com',
        phone: '010-3210-9876',
        name: '김미정',
        profile_image: 'ImageFile4',
      },
    },
  },
  {
    id: 5,
    status: '예약 확정',
    estimation: {
      id: 5,
      request_id: 18,
      expert_id: 19,
      location: '대전 유성구',
      due_date: '2024-12-20 13:30:00',
      service: '축가 가수',
      charge: 500000,
      created_at: '2024-11-12 15:45:00',
      request_user: {
        id: 18,
        name: '박성훈',
        phone: '010-4567-7890',
      },
      expert: {
        user_id: 19,
        email: 'singer@example.com',
        phone: '010-1112-2223',
        name: '최은영',
        profile_image: 'ImageFile5',
      },
    },
  },
  {
    id: 6,
    status: '서비스 완료',
    estimation: {
      id: 6,
      request_id: 21,
      expert_id: 25,
      location: '광주 북구',
      due_date: '2024-12-18 15:00:00',
      service: '영상 촬영',
      charge: 2000000,
      created_at: '2024-11-10 10:20:00',
      request_user: {
        id: 21,
        name: '정민호',
        phone: '010-7890-5678',
      },
      expert: {
        user_id: 25,
        email: 'videographer@example.com',
        phone: '010-5432-6789',
        name: '장수현',
        profile_image: 'ImageFile6',
      },
    },
  },
  {
    id: 7,
    status: '예약 취소',
    estimation: {
      id: 7,
      request_id: 27,
      expert_id: 29,
      location: '울산 남구',
      due_date: '2024-12-22 16:00:00',
      service: '축가 가수',
      charge: 3000000,
      created_at: '2024-11-08 11:30:00',
      request_user: {
        id: 27,
        name: '한지수',
        phone: '010-2345-6789',
      },
      expert: {
        user_id: 29,
        email: 'venue@example.com',
        phone: '010-6789-5432',
        name: '오승환',
        profile_image: 'ImageFile7',
      },
    },
  },
  {
    id: 8,
    status: '채팅 중',
    estimation: {
      id: 8,
      request_id: 33,
      expert_id: 35,
      location: '제주 제주시',
      due_date: '2024-12-28 12:00:00',
      service: '스냅 촬영',
      charge: 1200000,
      created_at: '2024-11-07 14:40:00',
      request_user: {
        id: 33,
        name: '이서윤',
        phone: '010-8765-1234',
      },
      expert: {
        user_id: 35,
        email: 'florist@example.com',
        phone: '010-2345-1234',
        name: '송하나',
        profile_image: 'ImageFile8',
      },
    },
  },
];
